feat(flyway repair,PIN-8259): implement optional flyway repair action (#69)
Co-authored-by: Michele De Simone <106953981+micdes-pagopa@users.noreply.github.com>

diff --git a/charts/interop-eks-microservice-chart/templates/deployment.yaml b/charts/interop-eks-microservice-chart/templates/deployment.yaml
--- a/charts/interop-eks-microservice-chart/templates/deployment.yaml
+++ b/charts/interop-eks-microservice-chart/templates/deployment.yaml
@@ -16,6 +16,20 @@
 {{ fail "One of deployment.image.tag and deployment.image.digest must be defined." }}
 {{- end }}
 
+{{- /* If the flyway initContainer is required then compute the flyway action(s) to execute */ -}}
+{{- $flyway_action := "" -}}
+{{- if and .Values.deployment .Values.deployment.flywayInitContainer .Values.deployment.flywayInitContainer.create }}
+{{- if and .Values.deployment.flywayInitContainer.executeFlywayMigrate .Values.deployment.flywayInitContainer.executeFlywayRepair -}}
+{{ $flyway_action = "repair-and-migrate" }}
+{{- else if .Values.deployment.flywayInitContainer.executeFlywayMigrate -}}
+{{ $flyway_action = "migrate" }}
+{{- else if .Values.deployment.flywayInitContainer.executeFlywayRepair -}}
+{{ $flyway_action = "repair" }}
+{{- else -}}
+{{- fail "Invalid configuration: Both executeFlywayMigrate and executeFlywayRepair in the flywayInitContainer are false." -}}
+{{- end -}}
+{{- end -}}
+
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -82,20 +96,39 @@ spec:
       initContainers:
         - name: migrate-db
           image: flyway/flyway:{{ .Values.deployment.flywayInitContainer.version}}
-          {{- if .Values.deployment.flywayInitContainer.downloadRedshiftDriver }}
           command:
             - /bin/sh
             - -c
             - |
-              echo "Downloading Redshift JDBC driver..."
-              curl -L -o /flyway/drivers/RedshiftJDBC.jar https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/2.1.0.32/redshift-jdbc42-2.1.0.32.jar
-              echo "Starting Flyway migration..."
-              flyway migrate
-          {{- else }}
-          args:
-            - migrate
-          {{- end }}
+              if [ "$INTERNAL_DOWNLOAD_REDSHIFT_DRIVER" = "true" ]; then
+                echo "Downloading Redshift JDBC driver..."
+                curl -L -o /flyway/drivers/RedshiftJDBC.jar https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/2.1.0.32/redshift-jdbc42-2.1.0.32.jar
+              else
+                echo "Skip Redshift JDBC driver download."
+              fi
+              case "$INTERNAL_FLYWAY_ACTION" in
+                "repair")
+                  echo "Starting Flyway repair..."
+                  flyway repair
+                  ;;
+                "repair-and-migrate")
+                  echo "Starting Flyway repair && migration ..."
+                  flyway repair && flyway migrate
+                  ;;
+                "migrate")
+                  echo "Starting Flyway migration..."
+                  flyway migrate
+                  ;;
+                *)
+                  echo "ERROR: Unknown flyway action: $INTERNAL_FLYWAY_ACTION"
+                  exit 1
+                  ;;
+              esac
           env:
+            - name: INTERNAL_DOWNLOAD_REDSHIFT_DRIVER
+              value: "{{ ternary "true" "false" .Values.deployment.flywayInitContainer.downloadRedshiftDriver }}"
+            - name: INTERNAL_FLYWAY_ACTION
+              value: "{{- $flyway_action }}"
             {{- if .Values.deployment.flywayInitContainer.envFromConfigmaps }}
             {{- range $key, $val := .Values.deployment.flywayInitContainer.envFromConfigmaps -}}
             {{- $renderedVal := include "interop-eks-microservice-chart.render-template" (dict "value" $val "context" $) }}
